language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenmpi-dev
      - openmpi-bin
      - python3-dev
      - python3-numpy
      - libblas-dev
      - liblapack-dev

env:
  global:
    - HWLOC_HIDE_ERRORS=1
    - PRECICE_ROOT="$TRAVIS_BUILD_DIR"
    - LOCAL_INSTALL="$HOME/local"
    - PETSC_ARCH=arch-linux2-c-debug
    - PETSC_DIR=$LOCAL_INSTALL/petsc
    - EIGEN3_ROOT_DIR=${LOCAL_INSTALL}/eigen3
    - CPLUS_INCLUDE_PATH="$PETSC_DIR/include:$PETSC_DIR/$PETSC_ARCH/include:$LOCAL_INSTALL/include:$EIGEN3_ROOT_DIR:$CPLUS_INCLUDE_PATH"
    - LD_LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LD_LIBRARY_PATH"
    - LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LIBRARY_PATH"
    - PYTHONPATH="$PETSC_DIR/$PETSC_ARCH/lib:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/plat-x86_64-linux-gnu"
    - BOOST_ROOT=${LOCAL_INSTALL}
    - CXXFLAGS="-Wall -Wextra -Wno-unused-parameter"
    - BOOST_TEST_LOG_LEVEL=test_suite

  matrix:
    - MPI=on PETSC=on
    - MPI=on PETSC=off
    - MPI=off PETSC=off

cache:
  ccache: true
  directories:
    - $LOCAL_INSTALL

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" && export CC="gcc-6" && export CXXFLAGS="$CXXFLAGS -Wno-literal-suffix"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi
  - pyenv versions
  - pyenv global 3.6.3
  - PYTHONPATH=""  # if PYTHONPATH is set, Travis errors
  - PY_CMD=python3  # set PY_CMD
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools # install python dependencies

install:
  - $TRAVIS_BUILD_DIR/tools/ci/travis-install-dependencies.sh $LOCAL_INSTALL
  - pip3 install --user cython numpy mpi4py packaging
  - export PATH=${LOCAL_INSTALL}/cmake/bin:${LOCAL_INSTALL}/bin:${PATH}

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - $TRAVIS_BUILD_DIR/tools/ci/travis-build-test.sh

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat -n ./tests/boost-test-output*
